# Generated by Django 2.1.4 on 2018-12-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HallPass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='Student_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
