# Generated by Django 2.1.4 on 2018-12-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HallPass', '0002_studentsession_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomleave',
            name='Student_ID',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='classroomreturn',
            name='Student_ID',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_ID',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='Student_ID',
            field=models.PositiveIntegerField(),
        ),
    ]
